Check state of database connection on error and exit if it is unusable
neicnordic/sda-pipeline pull request #162
Opened 2020-10-27 17:48 UTC by pontus

2020-10-27 19:11 UTC, blankdots approved these changes

2020-10-28 07:50 UTC, jbygdell commented
```diff --git a/internal/database/db.go b/internal/database/db.go
index 045a073..7fda164 100644
--- a/internal/database/db.go
+++ b/internal/database/db.go
@@ -11,4 +11,5 @@ import (
        "path/filepath"
        "strings"
+       "time"
 
        log "github.com/sirupsen/logrus"
@@ -28,5 +29,6 @@ type Database interface {
 // SQLdb struct that acts as a receiver for the DB update methods
 type SQLdb struct {
-       DB *sql.DB
+       DB       *sql.DB
+       ConnInfo string
 }
 
@@ -76,5 +78,5 @@ func NewDB(config DBConf) (*SQLdb, error) {
        }
 
-       return &SQLdb{DB: db}, nil
+       return &SQLdb{DB: db, ConnInfo: connInfo}, nil
 }
 
@@ -103,4 +105,21 @@ func buildConnInfo(config DBConf) string {
 }
 
+// Ping verifies a connection to the database is still alive,
+// establishing a connection if necessary.
+func (dbs *SQLdb) ping() (*sql.DB, error) {
+       db := dbs.DB
+       if err := db.Ping(); err != nil {
+               db.Close()
+               time.Sleep( 5 * time.Second)
+               log.Debugf("reconnecting to DB with <%s>", dbs.ConnInfo)
+               db, err := sqlOpen("postgres", dbs.ConnInfo)
+               if err != nil {
+                       return nil, err
+               }
+               return db, nil
+       }
+       return db, nil
+}
+
 // GetHeader retrieves the file header
 func (dbs *SQLdb) GetHeader(fileID int) ([]byte, error) {
@@ -218,5 +237,15 @@ func (dbs *SQLdb) MapFilesToDataset(datasetID string, accessionIDs []string) err
        const getID = "SELECT file_id FROM local_ega.archive_files WHERE stable_id = $1"
        const mapping = "INSERT INTO local_ega_ebi.filedataset (file_id, dataset_stable_id) VALUES ($1, $2);"
-       db := dbs.DB
+
+       log.Debugln("ping database")
+       db, err := dbs.ping()
+       if err != nil {
+               log.Errorf("database unreachable, reason: %v", err)
+       }
+       if err := db.Ping(); err != nil {
+               log.Errorf("ping error: %v", err)
+       }
+
+       log.Debugln("start transaction")
        var fileID int64
        transaction, _ := db.Begin()```

2020-11-01 10:09 UTC, jbygdell requested changes

2020-11-01 10:09 UTC, jbygdell commented on internal/database/db.go
>  	db := dbs.DB
Missing check.

```suggestion
	dbs.checkAndReconnectIfNeeded()

	db := dbs.DB
```

2020-11-02 07:45 UTC, pontus commented
I'm getting rid of checkAndAbortOnBadConn and using wrappers for all calls that retries a number of times before giving up. I'm happy to take opinions on that.

2020-11-05 07:44 UTC, jbygdell commented
> I'm thinking of getting rid of checkAndAbortOnBadConn and using wrappers for all calls that retries a number of times before giving up. I'm happy to take opinions on that.

Plan to do this in this PR?

2020-11-05 07:44 UTC, jbygdell approved these changes

2020-11-05 10:04 UTC, pontus commented
Open to suggestions, but currently, I'm leaning towards merging this and do a new PR for what we want.

2020-11-05 10:07 UTC, blankdots commented
I suggest a new PR so that we can move this forward

2020-11-05 12:07 UTC, merged