add sync service to main readme
neicnordic/sda-pipeline pull request #232
Opened 2021-01-19 16:21 UTC by blankdots

fix also some formatting

2021-01-19 16:37 UTC, jonandernovella approved these changes

2021-01-19 16:37 UTC, jonandernovella commented on README.md
> +| mapper        | The mapper service register mapping of _accessionIDs_ (IDs for files) to _datasetIDs_. |
```suggestion
| mapper        | The mapper service registers the mapping of _accessionIDs_ (IDs for files) to _datasetIDs_. |
```

2021-01-19 16:38 UTC, jonandernovella requested changes
Minor syntax suggestions

2021-01-19 17:09 UTC, pontus approved these changes

2021-01-25 11:30 UTC, jonandernovella approved these changes

2021-01-25 11:30 UTC, merged