Docker compose without TLS
neicnordic/sda-pipeline pull request #327
Opened 2021-12-09 10:39 UTC by jbygdell

Addition of a Docker Compose setup with TLS disabled including a simple integration test

2021-12-09 13:17 UTC, blankdots reviewed
is there any way to add another strategy to https://github.com/neicnordic/sda-pipeline/blob/master/.github/workflows/integration.yml for no-tls and maybe some `README.md` instructions - pretty please

2021-12-09 14:58 UTC, blankdots approved these changes

2021-12-10 19:46 UTC, blankdots requested changes

2021-12-10 19:46 UTC, blankdots commented on .github/workflows/integration.yml
> +        storagetype: [s3, posix, s3notls,]
forgotten comma ?
```suggestion
        storagetype: [s3, posix, s3notls]
```

2021-12-10 19:46 UTC, blankdots approved these changes
meant to approve it, that comma I am fine if it is there :)

2021-12-13 10:02 UTC, norling approved these changes
Can we use the compose v2 syntax, just to be on the newer version? Otherwise - looks good!

2021-12-13 15:47 UTC, blankdots reviewed
just noticed this: are these lines needed any more https://github.com/neicnordic/sda-pipeline/pull/327/files#diff-d4426dbe2254f7946e706886a3f294a6d57e1098c1ddb2e9a056f510ada5ca2cR25-R27 ?

https://github.com/neicnordic/sda-pipeline/blob/master/dev_utils/run_tests.sh and this ?

2021-12-14 08:24 UTC, a-ghanem approved these changes
Cannot say for sure as Norway is not using `docker-compose` in our deployment.

2021-12-16 07:04 UTC, blankdots commented
all positive reviews, merging

2021-12-16 07:04 UTC, merged