Adds config and communication to service docs
neicnordic/sda-pipeline pull request #513
Opened 2023-01-18 13:15 UTC by norling

Adds service configuration information to the pipeline services.

2023-01-18 16:10 UTC, blankdots approved these changes

2023-01-19 10:42 UTC, aaperis reviewed
Looks good, except from some cp-paste typos :)

2023-01-19 10:42 UTC, aaperis commented on cmd/backup/backup.md
> +There are a number of options that can be set for the verify service.
```suggestion
There are a number of options that can be set for the backup service.
```

2023-01-19 10:42 UTC, aaperis commented on cmd/backup/backup.md
> +   Note that if `DB_SSLMODE` is set to anything by `disable`, then `DB_CACERT` needs to be set,
```suggestion
   Note that if `DB_SSLMODE` is set to anything but `disable`, then `DB_CACERT` needs to be set,
```

2023-01-19 10:42 UTC, aaperis commented on cmd/backup/backup.md
> +The value of these variables define what other varaibles are read.
```suggestion
The value of these variables define what other variables are read.
```

2023-01-19 10:42 UTC, aaperis commented on cmd/finalize/finalize.md
> +There are a number of options that can be set for the verify service.
```suggestion
There are a number of options that can be set for the finalize service.
```

2023-01-19 10:42 UTC, aaperis commented on cmd/intercept/intercept.md
> +There are a number of options that can be set for the verify service.
```suggestion
There are a number of options that can be set for the intercept service.
```

2023-01-19 10:42 UTC, aaperis commented on cmd/finalize/finalize.md
> +   Note that if `DB_SSLMODE` is set to anything by `disable`, then `DB_CACERT` needs to be set,
```suggestion
   Note that if `DB_SSLMODE` is set to anything but `disable`, then `DB_CACERT` needs to be set,
```

2023-01-19 10:42 UTC, aaperis commented on cmd/ingest/ingest.md
> +   Note that if `DB_SSLMODE` is set to anything by `disable`, then `DB_CACERT` needs to be set,
```suggestion
   Note that if `DB_SSLMODE` is set to anything but `disable`, then `DB_CACERT` needs to be set,
```

2023-01-19 10:42 UTC, aaperis commented on cmd/intercept/intercept.md
> +   Note that if `DB_SSLMODE` is set to anything by `disable`, then `DB_CACERT` needs to be set,
```suggestion
   Note that if `DB_SSLMODE` is set to anything but `disable`, then `DB_CACERT` needs to be set,
```

2023-01-19 10:42 UTC, aaperis commented on cmd/mapper/mapper.md
> +   Note that if `DB_SSLMODE` is set to anything by `disable`, then `DB_CACERT` needs to be set,
```suggestion
   Note that if `DB_SSLMODE` is set to anything but `disable`, then `DB_CACERT` needs to be set,
```

2023-01-19 10:42 UTC, aaperis commented on cmd/verify/verify.md
> +   Note that if `DB_SSLMODE` is set to anything by `disable`, then `DB_CACERT` needs to be set,
```suggestion
   Note that if `DB_SSLMODE` is set to anything but `disable`, then `DB_CACERT` needs to be set,
```

2023-01-19 10:42 UTC, aaperis commented on cmd/mapper/mapper.md
> +There are a number of options that can be set for the verify service.
```suggestion
There are a number of options that can be set for the mapper service.
```

2023-01-19 13:17 UTC, jbygdell submitted a review, later dismissed

2023-01-19 13:17 UTC, jbygdell commented on cmd/backup/backup.md
> +These settings control how ingest connects to the RabbitMQ message broker.
```suggestion
These settings control how backup connects to the RabbitMQ message broker.
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/backup/backup.md
> + - `*_CACERT`: Certificate Authority (CA) certificate for the storage system
```suggestion
# CA certificate is only needed if the S3 server has a certificate signed by a private entity
 - `*_CACERT`: Certificate Authority (CA) certificate for the storage system
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/finalize/finalize.md
> +These settings control how ingest connects to the RabbitMQ message broker.
```suggestion
These settings control how finalize connects to the RabbitMQ message broker.
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/ingest/ingest.md
> + - `*_CACERT`: Certificate Authority (CA) certificate for the storage system
```suggestion
# CA certificate is only needed if the S3 server has a certificate signed by a private entity
 - `*_CACERT`: Certificate Authority (CA) certificate for the storage system
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/finalize/finalize.md
> + - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `archived`)
```suggestion
 - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `completed`)
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/verify/verify.md
> + - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `archived`)
```suggestion
 - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `verified`)
 # if `backup` is deployed the routing key should be `backup`
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/backup/backup.md
> + - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `archived`)
```suggestion
 - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `verified`)
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/verify/verify.md
> + - `*_CACERT`: Certificate Authority (CA) certificate for the storage system
```suggestion
# CA certificate is only needed if the S3 server has a certificate signed by a private entity
 - `*_CACERT`: Certificate Authority (CA) certificate for the storage system
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/intercept/intercept.md
> +These settings control how ingest connects to the RabbitMQ message broker.
```suggestion
These settings control how intercept connects to the RabbitMQ message broker.
```

2023-01-19 13:17 UTC, jbygdell commented on cmd/mapper/mapper.md
> +These settings control how ingest connects to the RabbitMQ message broker.
```suggestion
These settings control how mapper connects to the RabbitMQ message broker.
```

2023-01-31 11:55 UTC, kostas-kou approved these changes
Looks good to me and I agree with the comments of the other reviewers

2023-02-01 07:54 UTC, kjellp approved these changes
Looks good.

Seems like the default routingkey setting docs now indicate that the backup service should come after ingest and before verify? The overview schema on the front-page indicates ingest->verify->backup->finalize, so this is not fully in sync now.

2023-02-01 08:24 UTC, norling commented
I honestly don't know the "intended" order of backup :D if anyone knows - please update with some comment!

2023-02-01 14:19 UTC, blankdots requested changes
following the sda-helm deployment

i think the flow is  `ingest`->`verify`->`finalize`-> `backup` and ->`mapper` happens at some point after finalize

2023-02-01 14:19 UTC, blankdots commented on cmd/finalize/finalize.md
> + - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `completed`)
```suggestion
 - `BROKER_ROUTINGKEY`: message queue to write success messages to (commonly `backup`)
```

2023-02-01 14:19 UTC, blankdots commented on cmd/verify/verify.md
> + # if `backup` is deployed the routing key should be `backup`
```suggestion
```

2023-02-03 08:37 UTC, blankdots approved these changes

2023-02-03 13:25 UTC, pontus commented on cmd/mapper/mapper.md
> + - Mapper maps files to datasets in the database using thre `MapFilesToDataset` function.
```suggestion
 - Mapper maps files to datasets in the database using the `MapFilesToDataset` function.
```

2023-02-03 13:31 UTC, pontus approved these changes

2023-02-03 13:33 UTC, pontus commented
I think this is a clear improvement and don't see any issues that should block merging.

Possibly, one might consider moving all common configuration to one place rather than having it repeated all over (and risk missing updating things somewhere when adding new).

2023-02-06 12:42 UTC, merged