Allow for setting message prefetch number
neicnordic/sda-pipeline pull request #585
Opened 2023-05-24 11:44 UTC by jbygdell

This fixes an issue when the queue contains to many messages and the time for processing each message takes so long that acking a message not being worked on times out after 30min.

- default number of messages to retrieve from the server is set to 2
- setting the prefetch number to 1 will allow for a true round-robin situation with multiple workers

Fixes #575

2023-05-24 16:08 UTC, blankdots approved these changes

2023-05-24 16:12 UTC, pontus approved these changes

2023-05-24 20:18 UTC, dbampalikis requested changes
The implementation looks good. However, would it be possible to either add some documentation about it and possibly add it to the config (and or the docker compose file) so that we remember the option and what it is supposed to do?

2023-05-25 06:28 UTC, jbygdell commented
> The implementation looks good. However, would it be possible to either add some documentation about it and possibly add it to the config (and or the docker compose file) so that we remember the option and what it is supposed to do?

That will come in the helm chart update

2023-05-25 08:22 UTC, dbampalikis commented
> > The implementation looks good. However, would it be possible to either add some documentation about it and possibly add it to the config (and or the docker compose file) so that we remember the option and what it is supposed to do?
> 
> That will come in the helm chart update

It should be possible to set it on a docker level too, right? Why wouldn't we add it to the config, to know that this is an option then?

2023-05-25 08:56 UTC, aaperis approved these changes
It looks good :-). There's no harm in adding the configuration variable in the local dev environment though, as Dimi suggested. Regardless if that means repeating the default value, it may make life easier for future development.

2023-05-25 09:32 UTC, dbampalikis approved these changes

2023-05-29 05:02 UTC, merged

2023-05-29 05:23 UTC, blankdots commented
i merged this, looked like it was ready, sry if it shouldn't have been merged :(