unittests broker
neicnordic/sda-pipeline pull request #64
Opened 2020-08-11 18:59 UTC by blankdots

2020-08-18 14:05 UTC, pontus commented
100% coverage at least. 

Noticed a few cases where I considered if one wanted to change the current behaviour without wanting to decide.

Also, two distinct approaches with a mock server originally brought in from s3-upload-proxy and a mocking of interfaces is now being used. I think that's okay for now, but one might want to unify that in the future.

2020-08-20 06:06 UTC, jbygdell requested changes
Don't use real MQ ports as it will fail if MQ is running locally

2020-08-20 06:06 UTC, jbygdell commented on internal/broker/broker_test.go
> +	5672,
```suggestion
	6565,
```

2020-08-20 06:06 UTC, jbygdell commented on internal/broker/broker_test.go
> +	expectedMsg := "dial tcp 127.0.0.1:5672: connect: connection refused"
```suggestion
	expectedMsg := "dial tcp 127.0.0.1:6565: connect: connection refused"
```

2020-08-20 07:34 UTC, jbygdell approved these changes

2020-08-20 07:35 UTC, merged